# Generated by Django 5.2.4 on 2025-09-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a clear passport-style photo', null=True, upload_to='employee_photos/%Y/%m/', verbose_name='Employee Photo'),
        ),
    ]
